remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Minimalistic
description: Much description. Such Wow
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Home Page
    link: ./
    sublist:
      - name: Usage
        link: ./#usage
      - name: Customizing
        link: ./#customizing
      - name: Customizing Sidebar
        link: ./#customizing-sidebar
      - name: Navigation
        link: ./#navigation
      - name: Example
        link: ./#example
      - name: Stylesheet
        link: ./#stylesheet
      - name: Credits
        link: ./#credits
  - name: Sample
    link: ./codelab.html
  - name: Sample
    link: ./another-page.html
    sublist:
      - name: Image
        link: ./another-page.html#small-image
